apiVersion: apps/v1
kind: Deployment
metadata:
  name: myladingpage-deployment
spec:
  selector:
    matchLabels:
      app: myladingpage
  replicas: 2
  template:
    metadata:
      labels:
        app: myladingpage
    spec:
      containers:
      - name: myladingpage
        image: iamjeffersonpino/landing-page:v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: myladingpage
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: myladingpage